#!/usr/bin/env node
/**
 * One-command orchestration for the local Regtest Lab.
 *
 *   npm run lab:up      generate ephemeral credentials, boot, health check, list endpoints
 *   npm run lab:seed    deterministic fixtures (mines past the derived activation height)
 *   npm run lab:status  service state plus the adapter status document
 *   npm run lab:test    run the critical read-only workflow expectations
 *   npm run lab:reset   down with volumes, up, seed: the same deterministic state again
 *   npm run lab:logs    follow compose logs
 *   npm run lab:down    stop everything
 *
 * Credentials are generated per up and kept only in lab/.env (gitignored).
 * Nothing here ever touches a mainnet key: the lab is regtest-only.
 */
import { spawnSync } from 'node:child_process'
import { randomBytes } from 'node:crypto'
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(here, '..')
const LAB = resolve(ROOT, 'lab')
const envFile = resolve(LAB, '.env')

function compose(args, { capture = false, logsOnFailure = false } = {}) {
  const result = spawnSync('docker', ['compose', ...args], {
    cwd: LAB,
    stdio: capture ? 'pipe' : 'inherit',
    shell: process.platform === 'win32',
    encoding: 'utf8',
  })
  if (result.status !== 0 && logsOnFailure) {
    // The stack did not come up: show why before exiting, the compose
    // summary alone only names the unhealthy service.
    spawnSync('docker', ['compose', 'logs', '--tail', '80'], {
      cwd: LAB,
      stdio: 'inherit',
      shell: process.platform === 'win32',
    })
  }
  if (result.status !== 0) {
    process.stderr.write(result.stderr ?? '')
    process.exit(result.status ?? 1)
  }
  return result.stdout
}

function ensureCredentials() {
  if (existsSync(envFile)) return readFileSync(envFile, 'utf8')
  const password = randomBytes(24).toString('hex')
  const contents = [
    '# Ephemeral regtest credentials generated by scripts/lab.mjs. Never commit real secrets here.',
    `LAB_RPC_PASSWORD=${password}`,
    'COMPOSE_PROJECT_NAME=atomicals-lab',
    '',
  ].join('\n')
  writeFileSync(envFile, contents)
  return contents
}

function credentials() {
  if (!existsSync(envFile)) return ensureCredentials()
  return readFileSync(envFile, 'utf8')
}

/** Environment for the host-side scripts: the generated RPC password. */
function hostEnv() {
  const values = readEnv(credentials())
  return { ...process.env, LAB_CORE_RPC: `http://lab:${values.LAB_RPC_PASSWORD}@127.0.0.1:18443` }
}

function readEnv(contents) {
  const values = {}
  for (const line of contents.split('\n')) {
    const match = line.match(/^([A-Z0-9_]+)=(.*)$/)
    if (match) values[match[1]] = match[2]
  }
  return values
}

async function healthCheck() {
  for (let attempt = 0; attempt < 60; attempt += 1) {
    try {
      const response = await fetch('http://127.0.0.1:3043/live')
      if (response.ok) {
        process.stdout.write('\nThe lab is up. Endpoints:\n')
        process.stdout.write('  Bitcoin Core RPC (regtest): http://127.0.0.1:18443 (user lab, password in lab/.env)\n')
        process.stdout.write('  ElectrumX (electrum):       tcp://127.0.0.1:51001\n')
        process.stdout.write('  Read-only ARC-20 adapter:   http://127.0.0.1:3043\n')
        process.stdout.write('  Next step: npm run lab:seed\n')
        return
      }
    } catch {
      // not ready yet
    }
    await new Promise((resolve) => setTimeout(resolve, 2000))
  }
  process.stderr.write('The adapter did not become healthy in time. Run npm run lab:logs.\n')
  process.exit(1)
}

const command = process.argv[2] ?? ''

switch (command) {
  case 'up': {
    ensureCredentials()
    compose(['up', '-d', '--wait'], { logsOnFailure: true })
    await healthCheck()
    break
  }
  case 'seed': {
    credentials()
    spawnSync('node', [resolve(LAB, 'seed.mjs')], { stdio: 'inherit', env: hostEnv() })
    break
  }
  case 'status': {
    credentials()
    compose(['ps'])
    try {
      const response = await fetch('http://127.0.0.1:3043/token-explorer/status')
      process.stdout.write(`${JSON.stringify(await response.json(), null, 2)}\n`)
    } catch {
      process.stdout.write('adapter is not reachable; is the lab up?\n')
    }
    break
  }
  case 'test': {
    credentials()
    spawnSync('node', [resolve(LAB, 'run.mjs')], { stdio: 'inherit', env: hostEnv() })
    break
  }
  case 'reset': {
    credentials()
    compose(['down', '-v'])
    compose(['up', '-d', '--wait'], { logsOnFailure: true })
    await healthCheck()
    spawnSync('node', [resolve(LAB, 'seed.mjs')], { stdio: 'inherit', env: hostEnv() })
    break
  }
  case 'down': {
    credentials()
    compose(['down'])
    break
  }
  case 'logs': {
    credentials()
    compose(['logs', '-f', '--tail', '100'])
    break
  }
  default:
    process.stderr.write(`unknown lab command "${command}"\n`)
    process.exit(2)
}
